### ISSUE TITLE
Getting Started with Tennu - "Error: Cannot find module './command-handler'"

### ISSUE THREAD

**Issue by Zamiell** [Tennu/tennu#52]
Apologies for the noobish thread, but I did quite a bit of Googling and still couldn't resolve this problem. I'm following along with the documentation here: https://github.com/Tennu/tennu

After doing the following:

```
mkdir ircBot
cd ircBot
npm init
npm install tennu --save
echo "var tennu = require('tennu');" > bot.js
node bot.js
```

I get the following error, on both Linux and Windows:

```
module.js:338
    throw err;
          ^
Error: Cannot find module './command-handler'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (E:\Repositories\ZamielBot\node_modules\tennu\lib\inde
x.js:7:16)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (E:\Repositories\ZamielBot\bot.js:1:75)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
```

Is Tennu broken, or is the documentation missing some step?

**Comment by Zamiell** [comment]
Additionally, in the README.md file, the "See https://tennu.github.io/ for the full documentation" line should be taken out and/or updated, as the link in question is broken.

**Comment by Havvy** [comment]
Gah, I always forget about the index file. The command-handler was removed in v4.0.0 in favor of a plugin, but the index wasn't updated to remove that.

**Comment by Havvy** [comment]
The reason I didn't notice this is because I and the users I talk to often all use the `tennu` command line tool directly.

**Comment by Havvy** [comment]
I'm going to close this now. If you have any more questions related to the above, feel free to reopen or file a new issue.
