### ISSUE TITLE
Why doesnt my configuration work when using tennu in lib mode?

### ISSUE THREAD

**Issue by LordWingZero** [Tennu/tennu#59]
### myNetwork.conf:
```javascript
{
    "server": "Prothid.NY.US.GameSurge.Net",
    "password": null,
    "TLS":true,
    "port": 6697,
    "daemon": "irc2",
    "nicknames": ["BLTBot"],
    "username": "blt",
    "realname": "BLTBot in tennu",
    "channels": ["#successreactor"],
    "nickserv": "nickserv",
    "auth-password": null,
    "command-trigger": "!",
    "disable-help": false
}
```

### Index.js
```javascript
var tennu = require('tennu');

var network = require('./config/myNetwork.json'); // See next section

var myClient = tennu.Client(network);

myClient.connect();
```

### Error:
```bash
2015-11-06T21:51:37.789Z - notice: Tennu Connected
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at exports._errnoException (util.js:860:11)
    at TCP.onread (net.js:544:26)
```

**Comment by Havvy** [comment]
Is this still happening?

**Comment by LordWingZero** [comment]
```bash
ownix@WalnutPi ~/Cloud9/tennu-testing $ npm update
tennutest@1.0.0 /home/ownix/Cloud9/tennu-testing
└── tennu@4.5.0 

ownix@WalnutPi ~/Cloud9/tennu-testing $ node index.js 
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at exports._errnoException (util.js:860:11)
    at TCP.onread (net.js:544:26)
```

**Comment by Havvy** [comment]
Because TLS is true, and TLS is busted because I apparently don't know how to use TLS.

**Comment by LordWingZero** [comment]
I dont understand it either. Let me know if you get this figured out.
